### ISSUE TITLE
大佬 你那个swoole 的docker 里面的redis怎么用？

### ISSUE THREAD

**Issue by FlameMida** [drunker/docker-swoole-php#1]

**Comment by idrunk** [comment]
你怎么发到这个项目下啊.
redis在wiki.swoole里面有例子啊, 不过你得先安装并设置允许远程连接, 在那个docker镜像里面没有装redis的

**Comment by FlameMida** [comment]
> 你怎么发到这个项目下啊.
> redis在wiki.swoole里面有例子啊, 不过你得先安装并设置允许远程连接, 在那个docker镜像里面没有装redis的
是PHP 拓展里面的redis 不是swoole那个 我直接 new redis() 后他总是拒绝我连接 是服务没开么？

**Comment by idrunk** [comment]
> > 你怎么发到这个项目下啊.
> > redis在wiki.swoole里面有例子啊, 不过你得先安装并设置允许远程连接, 在那个docker镜像里面没有装redis的
> > 是PHP 拓展里面的redis 不是swoole那个 我直接 new redis() 后他总是拒绝我连接 是服务没开么？

嗯, 你得设置允许远程连接, 是redis服务器设置问题, 与你用哪个客户端连没关系
